<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GearFlow.Modules.Catalog.Contracts\GearFlow.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\GearFlow.Modules.Catalog.Domain\GearFlow.Modules.Catalog.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\Admin\" />
    <Folder Include="DTO\Public\" />
  </ItemGroup>

</Project>
