// <auto-generated />
using System;
using System.Collections.Generic;
using GearFlow.Modules.Reservations.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearFlow.Modules.Reservations.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(ReservationsDbContext))]
    [Migration("20260708131747_AddReservationStartDateConstraint")]
    partial class AddReservationStartDateConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reservations")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearFlow.Modules.Reservations.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedPaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TtlExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty<Dictionary<string, object>>("PaidAmount", "GearFlow.Modules.Reservations.Domain.Entities.Reservation.PaidAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("paid_amount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("paid_amount_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ReservedPeriod", "GearFlow.Modules.Reservations.Domain.Entities.Reservation.ReservedPeriod#DateRange", b1 =>
                        {
                            b1.Property<DateTime>("End")
                                .HasColumnType("date")
                                .HasColumnName("reserved_period_to");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("date")
                                .HasColumnName("reserved_period_from");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalPrice", "GearFlow.Modules.Reservations.Domain.Entities.Reservation.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_price_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Draft'");

                    b.ToTable("Reservations", "reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_ReservedPeriod_Start_NotBeforeCreatedAtUtcDate", "\"reserved_period_from\" >= ((\"CreatedAt\" AT TIME ZONE 'UTC')::date)");
                        });
                });

            modelBuilder.Entity("GearFlow.Modules.Reservations.Domain.Entities.ReservationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Item", "GearFlow.Modules.Reservations.Domain.Entities.ReservationLine.Item#OfferSnapshot", b1 =>
                        {
                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PriceSource")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PublicNote")
                                .HasColumnType("text");

                            b1.Property<string>("Size")
                                .HasColumnType("text");

                            b1.Property<Guid>("VariantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VariantName")
                                .HasColumnType("text");

                            b1.ComplexProperty<Dictionary<string, object>>("UnitPrice", "GearFlow.Modules.Reservations.Domain.Entities.ReservationLine.Item#OfferSnapshot.UnitPrice#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("unit_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_price_currency");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LineTotalPrice", "GearFlow.Modules.Reservations.Domain.Entities.ReservationLine.LineTotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("line_total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("line_total_price_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationLines", "reservations");
                });

            modelBuilder.Entity("GearFlow.Modules.Reservations.Domain.Entities.ReservationLine", b =>
                {
                    b.HasOne("GearFlow.Modules.Reservations.Domain.Entities.Reservation", "Reservation")
                        .WithMany("ReservationLines")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("GearFlow.Modules.Reservations.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("ReservationLines");
                });
#pragma warning restore 612, 618
        }
    }
}
