// <auto-generated />
using System;
using GearFlow.Modules.Catalog.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearFlow.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260706105004_CatalogInitial")]
    partial class CatalogInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EquipmentVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastMaintenanceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextInspectionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentVariantId");

                    b.ToTable("EquipmentItems", "catalog");
                });

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EquipmentModels", "catalog");
                });

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicNote")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentModelId");

                    b.ToTable("EquipmentVariants", "catalog");
                });

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentItem", b =>
                {
                    b.HasOne("GearFlow.Modules.Catalog.Domain.Entities.EquipmentVariant", "EquipmentVariant")
                        .WithMany()
                        .HasForeignKey("EquipmentVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentVariant");
                });

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentModel", b =>
                {
                    b.OwnsOne("GearFlow.Shared.Abstractions.ValueObjects.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("EquipmentModelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("base_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("base_price_currency");

                            b1.HasKey("EquipmentModelId");

                            b1.ToTable("EquipmentModels", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentModelId");
                        });

                    b.Navigation("BasePrice");
                });

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentVariant", b =>
                {
                    b.HasOne("GearFlow.Modules.Catalog.Domain.Entities.EquipmentModel", "EquipmentModel")
                        .WithMany("EquipmentVariants")
                        .HasForeignKey("EquipmentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GearFlow.Shared.Abstractions.ValueObjects.Money", "OverriddenPrice", b1 =>
                        {
                            b1.Property<Guid>("EquipmentVariantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("overridden_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("overridden_price_currency");

                            b1.HasKey("EquipmentVariantId");

                            b1.ToTable("EquipmentVariants", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentVariantId");
                        });

                    b.Navigation("EquipmentModel");

                    b.Navigation("OverriddenPrice");
                });

            modelBuilder.Entity("GearFlow.Modules.Catalog.Domain.Entities.EquipmentModel", b =>
                {
                    b.Navigation("EquipmentVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
