// <auto-generated />
using System;
using System.Collections.Generic;
using GearFlow.Modules.Rentals.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearFlow.Modules.Rentals.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(RentalsDbContext))]
    partial class RentalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rentals")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearFlow.Modules.Rentals.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty<Dictionary<string, object>>("LateFee", "GearFlow.Modules.Rentals.Domain.Entities.Rental.LateFee#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("late_fee_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("late_fee_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RentalPeriod", "GearFlow.Modules.Rentals.Domain.Entities.Rental.RentalPeriod#DateRange", b1 =>
                        {
                            b1.Property<DateTime>("End")
                                .HasColumnType("date")
                                .HasColumnName("rental_period_to");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("date")
                                .HasColumnName("rental_period_from");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalPrice", "GearFlow.Modules.Rentals.Domain.Entities.Rental.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("total_price_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Rentals", "rentals");
                });

            modelBuilder.Entity("GearFlow.Modules.Rentals.Domain.Entities.RentalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupConditionNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("PickupConditionRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnCondition")
                        .HasColumnType("text");

                    b.Property<string>("ReturnConditionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnConditionRecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("DamageFee", "GearFlow.Modules.Rentals.Domain.Entities.RentalLine.DamageFee#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("damage_fee_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("damage_fee_currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Item", "GearFlow.Modules.Rentals.Domain.Entities.RentalLine.Item#RentalItemSnapshot", b1 =>
                        {
                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PriceSource")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PublicNote")
                                .HasColumnType("text");

                            b1.Property<string>("Size")
                                .HasColumnType("text");

                            b1.Property<Guid>("VariantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("VariantName")
                                .HasColumnType("text");

                            b1.ComplexProperty<Dictionary<string, object>>("UnitPrice", "GearFlow.Modules.Rentals.Domain.Entities.RentalLine.Item#RentalItemSnapshot.UnitPrice#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("unit_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_price_currency");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("LineTotalPrice", "GearFlow.Modules.Rentals.Domain.Entities.RentalLine.LineTotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("line_total_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("line_total_price_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RentalId", "ReservationLineId")
                        .IsUnique();

                    b.ToTable("RentalLines", "rentals");
                });

            modelBuilder.Entity("GearFlow.Modules.Rentals.Domain.Entities.RentalLine", b =>
                {
                    b.HasOne("GearFlow.Modules.Rentals.Domain.Entities.Rental", "Rental")
                        .WithMany("RentalLines")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("GearFlow.Modules.Rentals.Domain.Entities.Rental", b =>
                {
                    b.Navigation("RentalLines");
                });
#pragma warning restore 612, 618
        }
    }
}
