// <auto-generated />
using System;
using System.Collections.Generic;
using GearFlow.Modules.Availability.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearFlow.Modules.Availability.Infrastructure.Migrations
{
    [DbContext(typeof(AvailabilityDbContext))]
    [Migration("20260706104927_AvailabilityInitial")]
    partial class AvailabilityInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("availability")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearFlow.Modules.Availability.Core.Entities.ItemBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("TimePeriod", "GearFlow.Modules.Availability.Core.Entities.ItemBooking.TimePeriod#DateRange", b1 =>
                        {
                            b1.Property<DateTime>("End")
                                .HasColumnType("date")
                                .HasColumnName("time_period_to");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("date")
                                .HasColumnName("time_period_from");
                        });

                    b.HasKey("Id");

                    b.ToTable("Bookings", "availability");
                });
#pragma warning restore 612, 618
        }
    }
}
